name: Send Docker Image
on:
  push:
  schedule:
    - cron: '0 10 * * Sun'
jobs:
  pull-latest-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: timvisee/send
          fetch-depth: 0
          ref: master
        
      - name: Set latest tag
        run: echo "LATEST_TAG=$(git describe --tags)" >> $GITHUB_ENV

      - name: Print tag
        run: echo ${{ env.LATEST_TAG }}

      - name: Checkout latest tag
        run: git checkout tags/${{ env.LATEST_TAG }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into Dockerhub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.server
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/send:${{ env.LATEST_TAG }}
